roles:
  ADMIN:
    permissions:
      - estimates:create
      - estimates:read
      - estimates:update
      - estimates:delete
      - users:manage
  MANAGER:
    permissions:
      - estimates:create
      - estimates:read
      - estimates:update
      - estimates:delete
  USER:
    permissions:
      - estimates:read