roles:
  ADMIN:
    permissions:
      - companies:create
      - companies:read
      - companies:update
      - companies:delete
      - estimates:create
      - estimates:read
      - estimates:update
      - estimates:delete
      - join_request:read
      - join_request:accept
      - join_request:reject
      - users:create
  MANAGER:
    permissions:
      - companies:read  # менеджеры могут читать компании (возможно, список своих компаний?)
      - estimates:create
      - estimates:read
      - estimates:update
      - estimates:delete
      - join_request:read
      - join_request:accept
      - join_request:reject
  USER:
    permissions:
      - companies:read
      - estimates:read