version: '3.8'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=185.239.51.126
#    depends_on:
#      - postgres
    networks:
      - app-network

#  postgres:
#    image: postgres:14-alpine
#    restart: unless-stopped
#    environment:
#      - POSTGRES_USER=${DB_USER}
#      - POSTGRES_PASSWORD=${DB_PASSWORD}
#      - POSTGRES_DB=${DB_NAME}
#    ports:
#      - "${DB_PORT}:5432"
#    volumes:
#      - postgres-data:/var/lib/postgresql/data
#    networks:
#      - app-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "3000:80"
    restart: unless-stopped
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
    driver: local
